# write a python program to show such type of layout of Number , and Square =>
print("Number\t\tSquareOfNumber")
# print(str(1)+"\t\t"+str(1 * 1))
# print(str(1)+"\t\t"+str(1 ** 2))
print(str(1)+"\t\t"+str(pow(1 , 2)))
# print(str(2)+"\t\t"+str(2 * 2))
# print(str(2)+"\t\t"+str(2 ** 2))
print(str(2)+"\t\t"+str(pow(2 , 2)))
# print(str(3)+"\t\t"+str(3 * 3))
# print(str(3)+"\t\t"+str(3 ** 2))
print(str(3)+"\t\t"+str(pow(3 , 2)))
# print(str(4)+"\t\t"+str(4 * 4))
# print(str(4)+"\t\t"+str(4 ** 2))
print(str(4)+"\t\t"+str(pow(4 , 2)))
# print(str(5)+"\t\t"+str(5 * 5))
# print(str(5)+"\t\t"+str(5 ** 2))
print(str(5)+"\t\t"+str(pow(5 , 2)))