# write a python program to show such type of layout of Number , Square , and Cube =>
print("Number\t\tSquareOfNumber\t\tCubeOfNumber")
# print(str(1)+"\t\t"+str(1 * 1)+"\t\t\t"+str(1 * 1 * 1))
# print(str(1)+"\t\t"+str(1 ** 2)+"\t\t\t"+str(1 ** 3))
print(str(1)+"\t\t"+str(pow(1 , 2))+"\t\t\t"+str(pow(1 , 3)))
# print(str(2)+"\t\t"+str(2 * 2)+"\t\t\t"+str(2 * 2 * 2))
# print(str(2)+"\t\t"+str(2 ** 2)+"\t\t\t"+str(2 ** 3))
print(str(2)+"\t\t"+str(pow(2 , 2))+"\t\t\t"+str(pow(2 , 3)))
# print(str(3)+"\t\t"+str(3 * 3)+"\t\t\t"+str(3 * 3 * 3))
# print(str(3)+"\t\t"+str(3 ** 2)+"\t\t\t"+str(3 ** 3))
print(str(3)+"\t\t"+str(pow(3 , 2))+"\t\t\t"+str(pow(3 , 3)))
# print(str(4)+"\t\t"+str(4 * 4)+"\t\t\t"+str(4 * 4 * 4))
# print(str(4)+"\t\t"+str(4 ** 2)+"\t\t\t"+str(4 ** 3))
print(str(4)+"\t\t"+str(pow(4 , 2))+"\t\t\t"+str(pow(4 , 3)))
# print(str(5)+"\t\t"+str(5 * 5)+"\t\t\t"+str(5 * 5 * 5))
# print(str(5)+"\t\t"+str(5 ** 2)+"\t\t\t"+str(5 ** 3))
print(str(5)+"\t\t"+str(pow(5 , 2))+"\t\t\t"+str(pow(5 , 3)))